# Generated by Django 5.2 on 2025-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('organizer', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
