# Generated by Django 5.2 on 2025-05-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
