# Generated by Django 5.2 on 2025-05-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_organizer_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=20)),
                ('subscribers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.club'),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
