# Generated by Django 5.2 on 2025-05-03 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('role', models.CharField(choices=[('student', 'Student'), ('club_head', 'HC')], default='student', max_length=9)),
                ('course', models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс')], max_length=1)),
                ('faculty', models.CharField(choices=[('FENS', 'Engineering'), ('BS', 'Business'), ('EDU', 'Education'), ('LSS', 'Law')], max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
