# Generated by Django 5.2 on 2025-05-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс')], max_length=1)),
                ('faculty', models.CharField(max_length=16)),
                ('role', models.CharField(choices=[('student', 'Student'), ('club_head', 'Head of Club')], default='student', max_length=10)),
            ],
        ),
    ]
